### PR TITLE
allow to log in via sso in the wiki

### PR DESCRIPTION
**Pull request by n0emis**

### CODE REVIEW

**Review by leona-ya — COMMENTED** [review]
Do we need the commented lines 79-80?

**Comment by n0emis** [comment]
We will need them after the 10.10.

**Comment by e1mo** [comment]
> We will need them after the 10.10.

I case you are referring to #41 , the 10.10. was just a placeholder.

**Comment by n0emis** [comment]
Ich setze das Datum mal auf den 21.10., das waere genau 4 Wochen nach dem Plenum.

**Review by leona-ya — APPROVED** [review]

**Review by e1mo — APPROVED** [review]

**Pull request merged**
